### ISSUE TITLE
Script Error When Adding Units to Zeus

### ISSUE THREAD

**Issue by Vauun** [Superxpdude/tmtm_template#24]
When the module is placed in Zeus to add units to the Zeus interface, a  scripting error for [XPT_fnc_curatorGrpPlaced] appears. The error appears every time the module is placed.

**Comment by Superxpdude** [comment]
Could you post the exact error itself from the .rpt file?

**Comment by Vauun** [comment]
` 2:58:46 Error in expression <PT_fnc_curatorGrpPlaced]"
params [
["_curator", nil, [objNull]],
[>
 2:58:46   Error position: <params [
["_curator", nil, [objNull]],
[>
 2:58:46   
Error Params: Type Object, expected Group
 2:58:46 File template\functions\curator\fn_curatorGrpPlaced.sqf [XPT_fnc_curatorGrpPlaced], line 14`

**Comment by k0machi** [comment]
https://github.com/Superxpdude/tmtm_template/blob/5568051b3e490a414b5d715f62ef89bce9594c15/template/functions/curator/fn_curatorGrpPlaced.sqf#L16
https://github.com/Superxpdude/tmtm_template/blob/5568051b3e490a414b5d715f62ef89bce9594c15/template/functions/curator/fn_curatorEH.sqf#L17
Unless modules send an object to that function, the issue is not present in `master`
It seems that you're using old version

**Comment by Superxpdude** [comment]
Issue appears to have already been fixed.

**Comment by Vauun** [comment]
After replacing `tmtm_template/template/functions/curator/fn_curatorGrpPlaced.sqf` with the most recent one on this repository the issue is still present.

**Comment by Superxpdude** [comment]
You need to replace the entire template folder when updating the template now. fn_curatorGrpPlaced.sqf is not the only file that has been changed.
